{% set name = "VapourSynth-CycMuNet" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - path: ../../tensorrt

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - cuda-nvcc
    - cuda-cudart-dev
    - libcublas-dev
    - cuda-cudart-static  # [linux]
    - sysroot_{{ target_platform  }}  >=2.17  # [linux]
  host:
    - cuda-cudart-dev
    - libnvinfer-dev
    - vapoursynth
  run:
    - cuda-cudart-dev  # [win]
    - cuda-cudart  # [linux]
    - libcublas-dev  #[win]
    - libcublas  # [linux]
    - libnvinfer
    - vapoursynth
  run_constrained:
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17  # [linux]

about:
  home: https://github.com/tongyuantongyu/cycmunet
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: VapourSynth plugin of CycMuNet+
  description: |
    VapourSynth plugin of CycMuNet+, a Spatio-Temporal Super Resolution Neural Network.
  dev_url: https://github.com/tongyuantongyu/cycmunet
  doc_url: https://github.com/tongyuantongyu/cycmunet/blob/main/tensorrt/README.md

extra:
  recipe-maintainers:
    - tongyuantongyu
